name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      
      - name: Python build
        run: |
          cd sneakydog-raspberrypi-demo
          pip install -r requirements.txt
          pip install build
          python -m build

      - name: Build the Docker Image ğŸ”§
        run: |
            docker build -t sneakydogs/sneakydog_raspberrypi_demo:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
  
      # - name: Push Docker image
      #   uses: ddocker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: sneakydogs/sneakydog_raspberrypi_demo:latest